name: MayoBlueSky-My-Actions-sync
on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: MayoBlueSky-My-Actions-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT || github.event.client_payload.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id || github.actor == 'BlueSkyClouds'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync MayoBlueSky-My-Actions
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/MayoBlueSky/My-Actions.git"
          source_branch: "master"
          destination_branch: "MayoBlueSky-My-Actions"
          github_token: ${{ secrets.PAT || github.event.client_payload.PAT }}